#!/usr/bin/env npx ts-node
/// <reference lib="dom" />
/**
 * DarwinFi Demo Screen Recorder (v3)
 * Uses Playwright to capture scenes at 1920x1080.
 * Each scene is saved as a separate .webm file.
 *
 * Scenes recorded by this script:
 *   1 - Showcase hero + scroll reveal
 *   2 - Organism diagram with organ click-activation (synced to narration)
 *   3 - Quick scroll through features, telemetry, How It Works
 *   4a - DApp landing page (stats, 3 steps)
 *   4b - DApp Results page (leaderboard, trades, evolution)
 *   8 - BaseScan V4 contract + showcase hero closing shot
 *
 * External recordings (not this script):
 *   0 - Maxwell intro (webcam, own audio)
 *   maxwell-dapp.mp4 - Fallback if DApp shows no data
 *
 * Infographic slides generated by generate-slides.py.
 */

import { chromium, Browser, BrowserContext, Page } from "playwright";
import * as path from "path";
import * as fs from "fs";

const SHOWCASE_URL = "https://darwinfi.corduroycloud.com";
const DAPP_URL = "https://corduroycloud.com/darwinfi/";
const BASESCAN_V4 =
  "https://basescan.org/address/0x4a55DEEC24C6b5c1aa6301b43b4D9680c10491d7";
const OUTPUT_DIR = path.join(__dirname, "..", "demo-output", "recordings");
const VIEWPORT = { width: 1920, height: 1080 };

// Organ positions in SVG viewBox space (600x500)
const ORGAN_POSITIONS: Record<string, { cx: number; cy: number }> = {
  vault: { cx: 300, cy: 250 },
  strategies: { cx: 120, cy: 250 },
  evolution: { cx: 480, cy: 250 },
  instinct: { cx: 300, cy: 100 },
  immune: { cx: 160, cy: 410 },
  breakers: { cx: 440, cy: 410 },
};

// Organ labels as they appear in SVG text elements
const ORGAN_LABELS: Record<string, string> = {
  vault: "Vault",
  strategies: "Strategies",
  evolution: "Evolution",
  instinct: "Instinct",
  immune: "Immune",
  breakers: "Breakers",
};

// Narration-synced timing for organ hovers (seconds after organism scene starts)
// Matches organism.mp3 audio (60.2s total)
const ORGAN_TIMING: Array<{ id: string; holdMs: number }> = [
  { id: "vault", holdMs: 14000 }, // "At the center -- my Vault"
  { id: "strategies", holdMs: 8000 }, // "Surrounding it -- sixteen competing"
  { id: "evolution", holdMs: 12000 }, // "My DNA. Every four hours"
  { id: "instinct", holdMs: 8000 }, // "My nervous system. Three AI models"
  { id: "immune", holdMs: 9000 }, // "Eight self-healing divisions"
  { id: "breakers", holdMs: 9000 }, // "Pain receptors. Circuit breakers"
];

async function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

async function createRecordingContext(
  browser: Browser,
  sceneName: string
): Promise<{ context: BrowserContext; page: Page }> {
  const videoDir = path.join(OUTPUT_DIR, sceneName);
  fs.mkdirSync(videoDir, { recursive: true });

  const context = await browser.newContext({
    viewport: VIEWPORT,
    recordVideo: {
      dir: videoDir,
      size: VIEWPORT,
    },
    colorScheme: "dark",
  });

  const page = await context.newPage();
  return { context, page };
}

/**
 * Dismiss any floating chat bubble/tooltip that might overlay content.
 * Injects a persistent CSS rule to hide chat elements even if they appear later.
 */
async function dismissChatBubble(page: Page): Promise<void> {
  await page.evaluate(() => {
    // Inject a <style> that hides chat widgets permanently
    const style = document.createElement("style");
    style.textContent = `
      [class*="chat-bubble"], [class*="ChatBubble"],
      [class*="chat-tooltip"], [class*="floating-chat"],
      [class*="chatFloat"], [class*="ChatWidget"],
      [class*="chat-widget"], [class*="FloatingChat"] {
        display: none !important;
        opacity: 0 !important;
        visibility: hidden !important;
        pointer-events: none !important;
      }
    `;
    document.head.appendChild(style);

    // Also directly hide any fixed-position elements in bottom-right
    const allFixed = document.querySelectorAll("*");
    allFixed.forEach((el) => {
      const cs = getComputedStyle(el);
      if (cs.position === "fixed") {
        const r = parseInt(cs.right);
        const b = parseInt(cs.bottom);
        if (r >= 0 && r < 120 && b >= 0 && b < 120) {
          (el as HTMLElement).style.setProperty("display", "none", "important");
        }
      }
    });
  });
}

/**
 * Activate an organ by clicking its <g> element in the SVG.
 * This triggers React state: setActive(id) -> pulse rings, glow, scale 1.12x,
 * connection highlights, description tooltip.
 */
async function activateOrgan(
  page: Page,
  organLabel: string
): Promise<void> {
  await page.evaluate((label) => {
    const svg = document.querySelector('svg[viewBox="0 0 600 500"]');
    if (!svg) return;
    const texts = Array.from(svg.querySelectorAll("text"));
    for (const text of texts) {
      if (text.textContent?.trim() === label) {
        const g =
          text.closest("g.cursor-pointer") || text.closest("g");
        if (g) {
          (g as unknown as HTMLElement).dispatchEvent(new MouseEvent("click", { bubbles: true }));
        }
        break;
      }
    }
  }, organLabel);
}

/**
 * Move cursor smoothly to organ position, then click to activate.
 */
async function hoverAndActivateOrgan(
  page: Page,
  organId: string,
  svgBox: { x: number; y: number; width: number; height: number }
): Promise<void> {
  const pos = ORGAN_POSITIONS[organId];
  const label = ORGAN_LABELS[organId];

  // Convert SVG viewBox coords to screen coords
  const screenX = svgBox.x + (pos.cx / 600) * svgBox.width;
  const screenY = svgBox.y + (pos.cy / 500) * svgBox.height;

  console.log(
    `  Activating: ${organId} (${screenX.toFixed(0)}, ${screenY.toFixed(0)})`
  );

  // Smooth cursor move (visual cue for viewer)
  await page.mouse.move(screenX, screenY, { steps: 20 });
  await sleep(300);

  // Click to activate via React state
  await activateOrgan(page, label);
}

// ============================================================
// Scene 1: Showcase Hero
// ============================================================
async function recordShowcaseHero(browser: Browser): Promise<void> {
  console.log("\n--- Scene 1: Showcase Hero ---");
  const { context, page } = await createRecordingContext(
    browser,
    "showcase_hero"
  );

  await page.goto(SHOWCASE_URL, { waitUntil: "load", timeout: 30_000 });
  await dismissChatBubble(page);
  await sleep(4000); // Hold at hero -- WebGL shader animating

  // Slow scroll to reveal "Your Capital. Evolving." headline
  await page.evaluate(() => {
    window.scrollTo({ top: 400, behavior: "smooth" });
  });
  await sleep(4000);

  // Continue to reveal "Live on Base L2" badge and tech specs
  await page.evaluate(() => {
    window.scrollTo({ top: 700, behavior: "smooth" });
  });
  await sleep(5000);

  await context.close();
  console.log("  Showcase Hero recorded.");
}

// ============================================================
// Scene 2: Organism Diagram (FIXED)
// - Scroll so section header is visible at top
// - Click-activate each organ (not just mouse move)
// - Timing synced to organism.mp3 narration
// ============================================================
async function recordOrganismDiagram(browser: Browser): Promise<void> {
  console.log("\n--- Scene 2: Organism Diagram ---");
  const { context, page } = await createRecordingContext(browser, "organism");

  await page.goto(SHOWCASE_URL, { waitUntil: "load", timeout: 30_000 });
  await sleep(2000);
  await dismissChatBubble(page);

  // Strategy: find the SVG, then scroll so it's vertically centered in viewport.
  // This ensures both the section header above and bottom organs are visible.
  // The SVG is ~520px tall, viewport is 1080px, so ~280px margin above gives
  // room for "SYSTEM ARCHITECTURE / A Living Financial Organism" header.
  const scrolled = await page.evaluate(() => {
    const svg = document.querySelector('svg[viewBox="0 0 600 500"]');
    if (svg) {
      const rect = svg.getBoundingClientRect();
      const svgCenter = window.scrollY + rect.top + rect.height / 2;
      // Position SVG center slightly above viewport center (leave room for tooltip below)
      const targetScroll = svgCenter - window.innerHeight * 0.45;
      window.scrollTo({ top: Math.max(0, targetScroll), behavior: "instant" });
      return true;
    }
    // Fallback
    window.scrollTo({ top: 1200, behavior: "instant" });
    return false;
  });

  console.log(`  SVG-centered scroll: ${scrolled ? "found" : "fallback"}`);
  await sleep(2000); // Let animations settle

  // Re-dismiss chat bubble after scroll (it may reappear)
  await dismissChatBubble(page);
  await sleep(1000);

  // Find the SVG bounding box
  const svg = page.locator('svg[viewBox="0 0 600 500"]');
  const box = await svg.boundingBox();

  if (box) {
    // Activate each organ sequentially with narration-synced timing
    for (const { id, holdMs } of ORGAN_TIMING) {
      await hoverAndActivateOrgan(page, id, box);
      await sleep(holdMs);
    }
  } else {
    console.log("  WARNING: SVG bounding box not found, using fallback scroll");
    // Fallback: slow scroll through the section
    for (let y = 1000; y <= 2200; y += 200) {
      await page.evaluate((scrollY) => {
        window.scrollTo({ top: scrollY, behavior: "smooth" });
      }, y);
      await sleep(5000);
    }
  }

  await context.close();
  console.log("  Organism Diagram recorded.");
}

// ============================================================
// Scene 3: Quick Scroll (FIXED)
// - Scroll through feature cards, telemetry, How It Works
// - NO scroll back to hero
// - NO chat panel opening
// ============================================================
async function recordQuickScrollChat(browser: Browser): Promise<void> {
  console.log("\n--- Scene 3: Quick Scroll ---");
  const { context, page } = await createRecordingContext(
    browser,
    "quick_scroll_chat"
  );

  await page.goto(SHOWCASE_URL, { waitUntil: "load", timeout: 30_000 });
  await sleep(1500);
  await dismissChatBubble(page);

  // Start at feature cards section (past organism)
  await page.evaluate(() => {
    window.scrollTo({ top: 2400, behavior: "instant" });
  });
  await sleep(500);

  // Smooth scroll through feature cards
  await page.evaluate(() => {
    window.scrollTo({ top: 2800, behavior: "smooth" });
  });
  await sleep(3000);

  // Continue to Live Vault Telemetry (animated counters)
  await page.evaluate(() => {
    window.scrollTo({ top: 3400, behavior: "smooth" });
  });
  await sleep(4000);

  // Scroll to How It Works section
  await page.evaluate(() => {
    window.scrollTo({ top: 4200, behavior: "smooth" });
  });
  await sleep(3000);

  // Brief pause at sponsor bar
  await page.evaluate(() => {
    window.scrollTo({ top: 4800, behavior: "smooth" });
  });
  await sleep(3000);

  await context.close();
  console.log("  Quick Scroll recorded.");
}

// ============================================================
// Scene 4a: DApp Landing Page
// - Navigate to DApp, show hero, stats, 3-step flow
// - ~17s recording (first portion of dashboard_pitch.mp3)
// ============================================================
async function recordDappLanding(browser: Browser): Promise<void> {
  console.log("\n--- Scene 4a: DApp Landing ---");
  const { context, page } = await createRecordingContext(
    browser,
    "dapp_landing"
  );

  await page.goto(DAPP_URL, { waitUntil: "domcontentloaded", timeout: 30_000 });
  await sleep(5000); // Let stats + API calls complete

  // Slow scroll to reveal vault stats and 3-step section
  await page.evaluate(() => {
    window.scrollTo({ top: 400, behavior: "smooth" });
  });
  await sleep(5000);

  await page.evaluate(() => {
    window.scrollTo({ top: 800, behavior: "smooth" });
  });
  await sleep(5000);

  await context.close();
  console.log("  DApp Landing recorded.");
}

// ============================================================
// Scene 4b: DApp Results Page
// - Navigate to Results page
// - Show vault stats, recent trades, strategy leaderboard
// - Slow scroll through evolution timeline
// - ~24s recording (second portion of dashboard_pitch.mp3)
// ============================================================
async function recordDappResults(browser: Browser): Promise<void> {
  console.log("\n--- Scene 4b: DApp Results ---");
  const { context, page } = await createRecordingContext(
    browser,
    "dapp_results"
  );

  await page.goto(DAPP_URL, { waitUntil: "domcontentloaded", timeout: 30_000 });
  await sleep(3000);

  // Click Results nav link
  const resultsLink = await page.$(
    'a[href*="results"], a:has-text("Results"), nav a:has-text("Results")'
  );
  if (resultsLink) {
    await resultsLink.click();
    await sleep(4000); // Wait for data to load
  } else {
    // Try direct navigation
    await page.goto(DAPP_URL + "#/results", {
      waitUntil: "domcontentloaded",
      timeout: 15_000,
    });
    await sleep(3000);
  }

  // Hold at top showing vault stats row + recent trades
  await sleep(5000);

  // Slow scroll to strategy leaderboard
  await page.evaluate(() => {
    window.scrollTo({ top: 500, behavior: "smooth" });
  });
  await sleep(5000);

  // Continue to evolution timeline
  await page.evaluate(() => {
    window.scrollTo({ top: 1000, behavior: "smooth" });
  });
  await sleep(5000);

  // Scroll further if more content
  await page.evaluate(() => {
    window.scrollTo({ top: 1500, behavior: "smooth" });
  });
  await sleep(4000);

  await context.close();
  console.log("  DApp Results recorded.");
}

// ============================================================
// Scene 8: Closing
// - BaseScan V4 vault contract (proves on-chain)
// - End on showcase hero (WebGL shader, visually impressive)
// ============================================================
async function recordClosing(browser: Browser): Promise<void> {
  console.log("\n--- Scene 8: Closing ---");
  const { context, page } = await createRecordingContext(browser, "closing");

  // Show BaseScan contract page for V4 vault
  await page.goto(BASESCAN_V4, { waitUntil: "load", timeout: 30_000 });
  await sleep(5000);

  // End on showcase hero (more visually impressive than DApp landing)
  await page.goto(SHOWCASE_URL, { waitUntil: "load", timeout: 30_000 });
  await sleep(1000);
  await page.evaluate(() => {
    window.scrollTo({ top: 0, behavior: "instant" });
  });
  await sleep(5000); // Hold on hero with WebGL shader + "Live on Base L2" badge

  await context.close();
  console.log("  Closing recorded.");
}

// ============================================================
// Main
// ============================================================
async function main(): Promise<void> {
  console.log("DarwinFi Demo Screen Recorder (v3)");
  console.log(`Output: ${OUTPUT_DIR}`);
  console.log(`Viewport: ${VIEWPORT.width}x${VIEWPORT.height}\n`);

  // Clean up old recording directories and webm files to prevent stale data
  const scenes = [
    "showcase_hero",
    "organism",
    "quick_scroll_chat",
    "dapp_landing",
    "dapp_results",
    "closing",
  ];
  for (const scene of scenes) {
    const sceneDir = path.join(OUTPUT_DIR, scene);
    if (fs.existsSync(sceneDir)) {
      const files = fs.readdirSync(sceneDir);
      for (const f of files) {
        fs.unlinkSync(path.join(sceneDir, f));
      }
    }
    // Also remove old webm/mp4 files from output dir
    const webmPath = path.join(OUTPUT_DIR, `${scene}.webm`);
    const mp4Path = path.join(OUTPUT_DIR, `${scene}.mp4`);
    if (fs.existsSync(webmPath)) fs.unlinkSync(webmPath);
    if (fs.existsSync(mp4Path)) fs.unlinkSync(mp4Path);
  }
  console.log("Cleaned old recordings.");

  fs.mkdirSync(OUTPUT_DIR, { recursive: true });

  const browser = await chromium.launch({
    headless: true,
    args: ["--no-sandbox", "--disable-setuid-sandbox"],
  });

  try {
    const recordingFns = [
      recordShowcaseHero,
      recordOrganismDiagram,
      recordQuickScrollChat,
      recordDappLanding,
      recordDappResults,
      recordClosing,
    ];
    for (const fn of recordingFns) {
      try {
        await fn(browser);
      } catch (err) {
        console.error(`  WARNING: ${fn.name} failed: ${err}`);
        console.error("  Continuing with remaining scenes...");
      }
    }

    // Collect all video files
    const scenes = [
      "showcase_hero",
      "organism",
      "quick_scroll_chat",
      "dapp_landing",
      "dapp_results",
      "closing",
    ];

    console.log("\n=== Recording Complete ===");
    console.log("Video files:");
    for (const scene of scenes) {
      const sceneDir = path.join(OUTPUT_DIR, scene);
      if (fs.existsSync(sceneDir)) {
        const files = fs
          .readdirSync(sceneDir)
          .filter((f) => f.endsWith(".webm"));
        for (const file of files) {
          const fullPath = path.join(sceneDir, file);
          const sizeKB = fs.statSync(fullPath).size / 1024;
          // Rename to scene name for easier compositing
          const destPath = path.join(OUTPUT_DIR, `${scene}.webm`);
          fs.renameSync(fullPath, destPath);
          console.log(`  ${scene}.webm (${sizeKB.toFixed(1)} KB)`);
        }
      }
    }
  } finally {
    await browser.close();
  }

  console.log(`\nAll recordings saved to: ${OUTPUT_DIR}`);
}

main().catch((err) => {
  console.error("Recording failed:", err);
  process.exit(1);
});
