#!/usr/bin/env npx ts-node
/**
 * DarwinFi Demo Screen Recorder (v2)
 * Uses Playwright to capture 4 scenes at 1920x1080.
 * Each scene is saved as a separate .webm file.
 *
 * Scene 0 (Maxwell's intro) -- recorded by Maxwell on webcam.
 * Scene 4 (DApp Dashboard) -- recorded by Maxwell with wallet connected.
 * Scenes 5-7 (infographics) -- generated by generate-slides.py.
 *
 * This script records: showcase hero, organism diagram, quick scroll+chat, closing.
 */

import { chromium, Browser, BrowserContext, Page } from "playwright";
import * as path from "path";
import * as fs from "fs";

const SHOWCASE_URL = "https://darwinfi.corduroycloud.com";
const DAPP_URL = "https://corduroycloud.com/darwinfi/";
const BASESCAN_V4 =
  "https://basescan.org/address/0x4a55DEEC24C6b5c1aa6301b43b4D9680c10491d7";
const OUTPUT_DIR = path.join(__dirname, "..", "demo-output", "recordings");
const VIEWPORT = { width: 1920, height: 1080 };

// Scene timing
const SCENE_CONFIG = {
  showcase_hero: { duration: 17_000, description: "Showcase hero + scroll reveal" },
  organism: { duration: 63_000, description: "Organism diagram with organ hovers" },
  quick_scroll_chat: { duration: 16_000, description: "Feature scroll + chatbot open/close" },
  closing: { duration: 13_000, description: "BaseScan V4 vault + dapp hero" },
};

// Organ positions in SVG viewBox space (600x500)
// These map to the OrganismDiagram SVG on the showcase site
const ORGAN_POSITIONS = {
  vault:      { cx: 300, cy: 250 },  // center
  strategies: { cx: 120, cy: 250 },  // left
  evolution:  { cx: 480, cy: 250 },  // right
  instinct:   { cx: 300, cy: 80 },   // top
  immune:     { cx: 140, cy: 420 },  // bottom-left
  breakers:   { cx: 460, cy: 420 },  // bottom-right
};

async function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

async function createRecordingContext(
  browser: Browser,
  sceneName: string
): Promise<{ context: BrowserContext; page: Page }> {
  const videoDir = path.join(OUTPUT_DIR, sceneName);
  fs.mkdirSync(videoDir, { recursive: true });

  const context = await browser.newContext({
    viewport: VIEWPORT,
    recordVideo: {
      dir: videoDir,
      size: VIEWPORT,
    },
    colorScheme: "dark",
  });

  const page = await context.newPage();
  return { context, page };
}

/**
 * Scene 1: Showcase Hero
 * Navigate to showcase, hold at hero, slow scroll to reveal headline and badges.
 */
async function recordShowcaseHero(browser: Browser): Promise<void> {
  console.log("\n--- Scene 1: Showcase Hero ---");
  const { context, page } = await createRecordingContext(browser, "showcase_hero");

  await page.goto(SHOWCASE_URL, { waitUntil: "load", timeout: 30_000 });
  await sleep(4000); // Hold at hero -- WebGL shader animating

  // Slow scroll to reveal "Your Capital. Evolving." headline
  await page.evaluate(() => {
    window.scrollTo({ top: 400, behavior: "smooth" });
  });
  await sleep(4000);

  // Continue to reveal "Live on Base L2" badge and tech specs
  await page.evaluate(() => {
    window.scrollTo({ top: 700, behavior: "smooth" });
  });
  await sleep(5000);

  await context.close();
  console.log("  Showcase Hero recorded.");
}

/**
 * Scene 2: Organism Diagram
 * Scroll to organism section, hover each organ sequentially (5-6s each).
 * Triggers pulse ring animations, connection path glows, description tooltips.
 */
async function recordOrganismDiagram(browser: Browser): Promise<void> {
  console.log("\n--- Scene 2: Organism Diagram ---");
  const { context, page } = await createRecordingContext(browser, "organism");

  await page.goto(SHOWCASE_URL, { waitUntil: "load", timeout: 30_000 });
  await sleep(3000);

  // Scroll to center the organism SVG in viewport
  const svgEl = await page.$('svg[viewBox="0 0 600 500"]');
  if (svgEl) {
    const rect = await svgEl.boundingBox();
    if (rect) {
      await page.evaluate(({ top, height }) => {
        window.scrollTo(0, top + window.scrollY + height / 2 - window.innerHeight / 2);
      }, rect);
    }
  } else {
    // Fallback: scroll to approximate position
    await page.evaluate(() => {
      window.scrollTo({ top: 1200, behavior: "smooth" });
    });
  }
  await sleep(3000);

  // Find the SVG element and get its bounding box
  const svg = page.locator('svg[viewBox="0 0 600 500"]');
  const box = await svg.boundingBox();

  if (box) {
    // Hover each organ sequentially
    const hoverOrder = ["vault", "strategies", "evolution", "instinct", "immune", "breakers"] as const;
    for (const organ of hoverOrder) {
      const pos = ORGAN_POSITIONS[organ];
      const screenX = box.x + (pos.cx / 600) * box.width;
      const screenY = box.y + (pos.cy / 500) * box.height;

      console.log(`  Hovering: ${organ} (${screenX.toFixed(0)}, ${screenY.toFixed(0)})`);
      await page.mouse.move(screenX, screenY, { steps: 20 }); // Smooth move
      await sleep(9000); // Hold for narration (fills 63s organism scene)
    }
  } else {
    console.log("  WARNING: SVG bounding box not found, using fallback scroll");
    // Fallback: just scroll through the section slowly
    for (let y = 1200; y <= 2200; y += 200) {
      await page.evaluate((scrollY) => {
        window.scrollTo({ top: scrollY, behavior: "smooth" });
      }, y);
      await sleep(5000);
    }
  }

  // Brief pause at the end
  await sleep(3000);

  await context.close();
  console.log("  Organism Diagram recorded.");
}

/**
 * Scene 3: Quick Scroll + Chatbot
 * Continue scrolling through feature cards, telemetry, How It Works.
 * Then open the floating chatbot, hold, close.
 */
async function recordQuickScrollChat(browser: Browser): Promise<void> {
  console.log("\n--- Scene 3: Quick Scroll + Chatbot ---");
  const { context, page } = await createRecordingContext(browser, "quick_scroll_chat");

  await page.goto(SHOWCASE_URL, { waitUntil: "load", timeout: 30_000 });
  await sleep(2000);

  // Scroll past organism to feature cards and telemetry
  await page.evaluate(() => {
    window.scrollTo({ top: 2500, behavior: "smooth" });
  });
  await sleep(3000);

  // Continue through live telemetry counters
  await page.evaluate(() => {
    window.scrollTo({ top: 3500, behavior: "smooth" });
  });
  await sleep(3000);

  // Scroll through How It Works
  await page.evaluate(() => {
    window.scrollTo({ top: 4500, behavior: "smooth" });
  });
  await sleep(2000);

  // Scroll back to top area to find chat bubble
  await page.evaluate(() => {
    window.scrollTo({ top: 0, behavior: "smooth" });
  });
  await sleep(2000);

  // Click the floating chat bubble (bottom-right)
  const chatBubble = await page.$(
    'button[class*="chat"], [data-testid="chat-bubble"], button:has-text("Chat"), [class*="floating-chat"]'
  );
  if (chatBubble) {
    await chatBubble.click();
    await sleep(3000); // Show chat panel with thinking indicator
    // Close chat
    const closeBtn = await page.$(
      'button[class*="close"], [data-testid="chat-close"], button:has-text("Close")'
    );
    if (closeBtn) {
      await closeBtn.click();
    }
  } else {
    console.log("  WARNING: Chat bubble not found, attempting bottom-right click");
    // Click bottom-right area where chat bubble typically is
    await page.mouse.click(1870, 1030);
    await sleep(3000);
  }

  await sleep(2000);

  await context.close();
  console.log("  Quick Scroll + Chatbot recorded.");
}

/**
 * Scene 8: Closing
 * BaseScan V4 vault contract (real txns), then back to DApp hero.
 */
async function recordClosing(browser: Browser): Promise<void> {
  console.log("\n--- Scene 8: Closing ---");
  const { context, page } = await createRecordingContext(browser, "closing");

  // Show BaseScan contract page for V4 vault
  await page.goto(BASESCAN_V4, { waitUntil: "load", timeout: 30_000 });
  await sleep(5000);

  // Navigate to dapp hero for final shot
  await page.goto(DAPP_URL, { waitUntil: "load", timeout: 30_000 });
  await sleep(5000);

  await page.evaluate(() => {
    window.scrollTo({ top: 0, behavior: "smooth" });
  });
  await sleep(2000);

  await context.close();
  console.log("  Closing recorded.");
}

async function main(): Promise<void> {
  console.log("DarwinFi Demo Screen Recorder (v2)");
  console.log(`Output: ${OUTPUT_DIR}`);
  console.log(`Viewport: ${VIEWPORT.width}x${VIEWPORT.height}\n`);

  fs.mkdirSync(OUTPUT_DIR, { recursive: true });

  const browser = await chromium.launch({
    headless: true,
    args: ["--no-sandbox", "--disable-setuid-sandbox"],
  });

  try {
    await recordShowcaseHero(browser);
    await recordOrganismDiagram(browser);
    await recordQuickScrollChat(browser);
    await recordClosing(browser);

    // Collect all video files
    console.log("\n=== Recording Complete ===");
    console.log("Video files:");
    for (const scene of Object.keys(SCENE_CONFIG)) {
      const sceneDir = path.join(OUTPUT_DIR, scene);
      if (fs.existsSync(sceneDir)) {
        const files = fs.readdirSync(sceneDir).filter((f) => f.endsWith(".webm"));
        for (const file of files) {
          const fullPath = path.join(sceneDir, file);
          const sizeKB = fs.statSync(fullPath).size / 1024;
          // Rename to scene name for easier compositing
          const destPath = path.join(OUTPUT_DIR, `${scene}.webm`);
          fs.renameSync(fullPath, destPath);
          console.log(`  ${scene}.webm (${sizeKB.toFixed(1)} KB)`);
        }
      }
    }
  } finally {
    await browser.close();
  }

  console.log(`\nAll recordings saved to: ${OUTPUT_DIR}`);
  console.log("\nNOTE: Scene 4 (DApp Dashboard) must be recorded by Maxwell");
  console.log("  with wallet connected -> save as demo-output/maxwell-dapp.mp4");
}

main().catch((err) => {
  console.error("Recording failed:", err);
  process.exit(1);
});
